services:
  php-backend:
    build:
      context: .
    container_name: php-backend-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: php-backend-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: project_mongo_db
    ports:
      - "23567:27017"
    volumes:
      - php-backend-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: php-backend-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_postgres_db
    ports:
      - "5555:5432"
    volumes:
      - php-backend-postgresql:/data/db/postgresql

volumes:
  php-backend-mongodb:
    driver: local
  php-backend-postgresql:
    driver: local
